packages:
  - "apps/*"
  - "packages/*"
overrides:
  '@eslint/js': 9.39.4
  '@typescript-eslint/eslint-plugin': 8.59.4
  '@typescript-eslint/parser': 8.59.4
  '@typescript-eslint/type-utils': 8.59.4
  '@typescript-eslint/typescript-estree': 8.59.4
  '@typescript-eslint/utils': 8.59.4
  eslint: 9.39.4
  typescript-eslint: 8.59.4
allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': true
  '@scarf/scarf': false
  '@swc/core': true
  argon2: false
  core-js: true
  core-js-pure: true
  esbuild: true
