packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': true
  '@scarf/scarf': false
  '@swc/core': true
  '@tarojs/binding': set this to true or false
  '@tarojs/cli': set this to true or false
  argon2: false
  core-js: true
  core-js-pure: true
  esbuild: true
